- project:
    check:
      jobs:
        - l2gw-tox-lower-constraints
    gate:
      jobs:
        - l2gw-tox-lower-constraints

- job:
    name: l2gw-tox-lower-constraints
    parent: openstack-tox-lower-constraints
    required-projects:
      - openstack/neutron
